/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import javax.swing.*;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.awt.Component;

/**
 *
 * @author marco
 */
public class Seleccion_de_personaje extends javax.swing.JFrame {

    private int players = 1;
    private int name_players = 2;
    private Map<String, JPanel> mapa = new HashMap<>();
    private List<JComboBox> bicho_elegido = new ArrayList<>();
    private List<JTextField> campos = new ArrayList<>();
    private List<JComboBox> ia_o_humano = new ArrayList<>();
    /**
     * Creates new form Seleccion_de_personaje
     */
    public Seleccion_de_personaje() {
        initComponents();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        campos.add(usuario);
        bicho_elegido.add(lista_bichos);
        ia_o_humano.add(pc_o_humano);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void eliminarActionPerformed(java.awt.event.ActionEvent evt)
    {
        JButton boton = (JButton) evt.getSource();
        JPanel panel = mapa.get(boton.getName());
        Component[] componentes = panel.getComponents();
        
        for (int i = 0; i < componentes.length; i++)
        {
            if (componentes[i] instanceof JTextField)
                campos.remove(componentes[i]);
            else if (componentes[i] instanceof JComboBox)
            {
                if (componentes[i].getName().equals("bichos"))
                    bicho_elegido.remove(componentes[i]);
                else
                    ia_o_humano.remove(componentes[i]);
            }
        }
        jPanel1.remove(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
        players--;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lista_bichos = new javax.swing.JComboBox<>();
        pc_o_humano = new javax.swing.JComboBox<>();
        usuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        aniadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        lista_bichos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "The King", "Alienoid", "Gigazaur", "Mekadragon", "Space Pinguin", "Boogie Woogie", "Pumping Jack", "Pandakai", "Cyber Kitty", " " }));

        pc_o_humano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "IA(Comming soon)" }));

        usuario.setText("Jugador1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lista_bichos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pc_o_humano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista_bichos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pc_o_humano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );

        jButton2.setText("Empezar Partida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        aniadir.setText("+");
        aniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(aniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirActionPerformed
        // TODO add your handling code here:
        if (players < 4)
        {
            JComboBox<String> combo = new JComboBox<>();
            combo.setName("bichos");
            /*The King
            Alienoid
            Gigazaur
            Mekadragon
            Space Pinguin
            Boogie Woogie
            Pumping Jack
            Pandakai
            Cyber Kitty
            */
            combo.addItem("The King");
            combo.addItem("Alienoid");
            combo.addItem("Gigazaur");
            combo.addItem("Mekadragon");
            combo.addItem("Space Pingui");
            combo.addItem("Boogie Woogie");
            combo.addItem("Pumping Jack");
            combo.addItem("Pandakai");
            combo.addItem("Cyber Kitty");
            JComboBox<String> combo2 = new JComboBox<>();
            combo2.setName("ia_o_humano");
            combo2.addItem("Humano");
            combo2.addItem("IA(Comming soon)");
            JTextField usuario = new JTextField();
            campos.add(usuario);
            usuario.setText("Jugador" + name_players);
            usuario.setName("Jugador" + name_players);
            JButton eliminar = new JButton();
            eliminar.setName(String.valueOf(name_players));
            eliminar.setText("-");
            eliminar.addActionListener(evt2 -> eliminarActionPerformed(evt2));
            JPanel panel2 = new JPanel();

            panel2.add(eliminar);
            panel2.add(usuario);
            panel2.add(combo);
            panel2.add(combo2);
            mapa.put(eliminar.getName(), panel2);
            jPanel1.add(panel2);
            jPanel1.revalidate();
            jPanel1.repaint();
            players++;
            name_players++;
        }
    }//GEN-LAST:event_aniadirActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu menu = new Menu();
    }//GEN-LAST:event_volverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (players <= 4 && players >= 2)
        {
            Partida partida = new Partida(players, campos, bicho_elegido, ia_o_humano);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniadir;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lista_bichos;
    private javax.swing.JComboBox<String> pc_o_humano;
    private javax.swing.JTextField usuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
